USE [master]
GO

/****** Object:  Database [BDJSL]    Script Date: 01/07/2021 08:35:56 ******/
CREATE DATABASE [BDJSL]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BDJSL', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BDJSL.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BDJSL_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BDJSL_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BDJSL].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BDJSL] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BDJSL] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BDJSL] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BDJSL] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BDJSL] SET ARITHABORT OFF 
GO

ALTER DATABASE [BDJSL] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BDJSL] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BDJSL] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BDJSL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BDJSL] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BDJSL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BDJSL] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BDJSL] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BDJSL] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BDJSL] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BDJSL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BDJSL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BDJSL] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BDJSL] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BDJSL] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BDJSL] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BDJSL] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BDJSL] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BDJSL] SET  MULTI_USER 
GO

ALTER DATABASE [BDJSL] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BDJSL] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BDJSL] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BDJSL] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BDJSL] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BDJSL] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BDJSL] SET  READ_WRITE 
GO

