//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSLProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veiculo
    {
        public string placa { get; set; }
        public string modelo { get; set; }
        public string marca { get; set; }
        public Nullable<int> eixos { get; set; }
        public int id_motorista { get; set; }
    
        public virtual Motorista Motorista { get; set; }
    }
}
