//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSLProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viagem
    {
        public int id_viagem { get; set; }
        public System.DateTime dataHora { get; set; }
        public int localEntrega { get; set; }
        public int localSaida { get; set; }
        public int distancia { get; set; }
        public Nullable<int> pesoCarga { get; set; }
        public Nullable<int> id_motorista { get; set; }
    
        public virtual Motorista Motorista { get; set; }
        public virtual Endereco Endereco { get; set; }
        public virtual Endereco Endereco1 { get; set; }
    }
}
